### ISSUE TITLE
Quick installation instructions in the README?

### ISSUE THREAD

**Issue by DivineDominion** [lsp-zettelkasten/lsp-zettelkasten#1]
It'd be cool to have instructions how to run the LSP server based on the JS output and how to connect to it from an environment you know (appears to be vim). Can probably extrapolate settings for other editors based on that, but any starting point would be super helpful 💪

**Comment by danymat** [comment]
Hello @DivineDominion, I added neovim installation instructions, I think it could be a starting point for you to try testing it. If you know how to integrate with your current editor, feel free to create a PR for it !

Keep me in touch, 
Sincerely, Daniel.

**Comment by DivineDominion** [comment]
Excellent, thanks!
